// 提示詞合集 Prompt 19 任務 B — design-tokens → Tailwind 同步
// ============================================================
// 讀 design-tokens/tokens.json → 產 design-tokens/tailwind.tokens.cjs
// (供 tailwind.config 的 theme.extend 引用、不直接覆寫既有 config)。
//
// 🔴 最小 blast radius:不改既有 tailwind.config(改全站樣式 config = P1
//   需驗證)。只產出可被引用的 token 檔;是否 import 進 tailwind.config
//   由老闆/staging 決定。Figma webhook 自動 PR = 外部整合 = 老闆。
//
// 跑法:node scripts/sync-tokens.mjs

import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'design-tokens')
const tokens = JSON.parse(readFileSync(join(DIR, 'tokens.json'), 'utf-8'))

const colors = Object.fromEntries(
  Object.entries(tokens.color || {}).map(([k, v]) => [k, v.value]),
)
const fontFamily = Object.fromEntries(
  Object.entries(tokens.font || {}).map(([k, v]) => [k, v.value.split(',').map((s) => s.trim())]),
)
const borderRadius = Object.fromEntries(
  Object.entries(tokens.radius || {}).map(([k, v]) => [k, v.value]),
)

const out = `// AUTO-GENERATED by scripts/sync-tokens.mjs — 勿手改
// tailwind.config.ts 用法:const t = require('./design-tokens/tailwind.tokens.cjs')
//   theme: { extend: { colors: t.colors, fontFamily: t.fontFamily, borderRadius: t.borderRadius } }
module.exports = ${JSON.stringify({ colors, fontFamily, borderRadius }, null, 2)}\n`

writeFileSync(join(DIR, 'tailwind.tokens.cjs'), out, 'utf-8')
console.log('[ok] design-tokens/tailwind.tokens.cjs(引用方式見檔頭註解、未自動改 tailwind.config)')
